#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# x = 0 = 1

x = "4"
x1 = "rock*4"
x2 = "lemon"
x3 = "Alcohol free drinks"
x4 = "False"
x5 = "LTE3"
x6 = "Another brick on the wall"
x7 = "Google without googling"
x8 = "A young friend with big dreams"
x9 = "Two young friends with big dreams"
x10 = "Dreaming awake might turn to trouble"
x11 = "A person who never talks"
x12 = "Two persons who never talk"
x13 = "A city that revolts"
x14 = "A European country in deep sleeping mode"
x15 = "Fear of the dark?"
x16 = "False"
x17 = "Two new friends that speak a little chinese"
x18 = "The bridges of Prague"
x19 = "An old synthesizer and a harmonica"
x20 = "Life would be an error without music"
x21 = "The solution must also be beautiful"
x22 = "But beauty is not only what we see but also inner"
x23 = "An ancient tragedy revived"
x24 = "The trick with the crazy person and chicken acting/doctors"
x25 = "Three persons that never talk"
x26 = "THE TEST OF THE DRAGON have you passed it?"
x27 = "THE TEST OF THE DRAGON have you passed it?"
x28 = "I am still alive so yes I've passed it"
x29 = "End of time"
y= "Amerika is a mistake"
y1 = "if relativity theory proves true Deutsch people will call me Deutsch and French will call me cosmopolitan. If relativity theory proves wrong French people will call me Deutsch and Deutsch people Jew"
y2 = "I believe the use of animals in experiments is an awful idea: they get furstrated and they give wrong anwers"
y3 = "have faith in progress. It's always right even if it's wrong"
y4 = "a balanced person is a peson who can do the same mistake twice without losing control"


print(bool(x))
print(bool(x1))
print(bool(x2))
print(bool(x3))
print(bool(x4))
print(bool(x5))
print(bool(x6))
print(bool(x7))
print(bool(x8))
print(bool(x9))
print(bool(x10))
print(bool(x11))
print(bool(x12))
print(bool(x13))
print(bool(x14))
print(bool(x15))
print(bool(x16))
print(bool(x17))
print(bool(x18))
print(bool(x19))
print(bool(x20))
print(bool(x21))
print(bool(x22))
print(bool(x23))
print(bool(x24))
print(bool(x25))
print("False")
print(bool(x27))
print(bool(x28))
print("False")
print(bool(y))
print(bool(y1))
print(bool(y2))
print(bool(y3))
print(bool(y4))
